// Generated from ReSkate Studio's blender_addon/sk8_map_export.py (AUDIO_TAG_PATHS, region group):
// the "Native Region" choices of an audio volume. Regenerate with tools/gen_studio_surfaces.py.
#pragma once

namespace xl {

struct StudioAudioRegion {
    const char* path;   // what sk8_audio_region_tag stores
    const char* label;
};

inline constexpr StudioAudioRegion kStudioAudioRegions[] = {
    {"audio/_systems/audiotag/region/dgo_spot_reg_isleofgrom_spillway_lower", "Dgo Spot Reg Isleofgrom Spillway Lower"},
    {"audio/_systems/audiotag/region/dgo_spot_reg_isleofgrom_spillway_ocean", "Dgo Spot Reg Isleofgrom Spillway Ocean"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_activities", "Reg Activities"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_building_church", "Reg Building Church"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_building_generic", "Reg Building Generic"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_building_mall", "Reg Building Mall"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_building_parkade_historic", "Reg Building Parkade Historic"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_building_stadium", "Reg Building Stadium"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_building_stadium_interior", "Reg Building Stadium Interior"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_district_downtown", "Reg District Downtown"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_elevatorhallway_svnnews_historic", "Reg Elevatorhallway Svnnews Historic"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_ftue_set01", "Reg Ftue Set01"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_ftue_set02", "Reg Ftue Set02"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_ftue_set03", "Reg Ftue Set03"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_ftue_set04", "Reg Ftue Set04"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_ftue_set05", "Reg Ftue Set05"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_ftue-island", "Reg Ftue-Island"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom", "Reg Isleofgrom"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set01", "Reg Isleofgrom Set01"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set01b", "Reg Isleofgrom Set01B"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set02", "Reg Isleofgrom Set02"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set03", "Reg Isleofgrom Set03"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set03b", "Reg Isleofgrom Set03B"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set4", "Reg Isleofgrom Set4"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_isleofgrom_set5", "Reg Isleofgrom Set5"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_megaramp_federalistblock", "Reg Megaramp Federalistblock"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr", "Reg Mpr"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_beach", "Reg Mpr Beach"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_chalet", "Reg Mpr Chalet"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_concourse", "Reg Mpr Concourse"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_forestpark", "Reg Mpr Forestpark"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_lowbowls", "Reg Mpr Lowbowls"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_lowramps", "Reg Mpr Lowramps"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_mountain", "Reg Mpr Mountain"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_pond", "Reg Mpr Pond"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_ravine", "Reg Mpr Ravine"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_upperramps", "Reg Mpr Upperramps"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_mpr_walkway", "Reg Mpr Walkway"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_nbhd_entertainmenthub", "Reg Nbhd Entertainmenthub"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_nbhd_financial", "Reg Nbhd Financial"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_nbhd_historic", "Reg Nbhd Historic"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_nbhd_stadium", "Reg Nbhd Stadium"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_alley", "Reg Plot Alley"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_halloweenpark", "Reg Plot Halloweenpark"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_park", "Reg Plot Park"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_pier", "Reg Plot Pier"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_plaza", "Reg Plot Plaza"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_residential", "Reg Plot Residential"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_seawall", "Reg Plot Seawall"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_shops", "Reg Plot Shops"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_skatepaddys", "Reg Plot Skatepaddys"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_skatepark", "Reg Plot Skatepark"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_plot_winterpark", "Reg Plot Winterpark"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_popups", "Reg Popups"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_amphitheater", "Reg Spot Amphitheater"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_blockparty", "Reg Spot Blockparty"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_casperhotel", "Reg Spot Casperhotel"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_cementery", "Reg Spot Cementery"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_collabzone_plot32", "Reg Spot Collabzone Plot32"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_firestation", "Reg Spot Firestation"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_funnel", "Reg Spot Funnel"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_halloweenpark_underground", "Reg Spot Halloweenpark Underground"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_pivotrooftop", "Reg Spot Pivotrooftop"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_playground", "Reg Spot Playground"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_rooftop_plot03", "Reg Spot Rooftop Plot03"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_rooftop_plot12", "Reg Spot Rooftop Plot12"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_season1_canal", "Reg Spot Season1 Canal"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_spot_warehouse_empty", "Reg Spot Warehouse Empty"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_vehicleunderpass", "Reg Vehicleunderpass"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_water_canal", "Reg Water Canal"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_water_ocean", "Reg Water Ocean"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_water_river", "Reg Water River"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_water_river_underground", "Reg Water River Underground"},
    {"audio/_systems/audiotag/region/dgo_tag_reg_water_waterfall", "Reg Water Waterfall"},
    {"audio/_systems/audiotag/region/dgo_tag_spot_isleofgrom_spillway_upper", "Spot Isleofgrom Spillway Upper"},
    {"audio/_systems/audiotag/region/dgo_tag_spot_isleofgrom_tunnel", "Spot Isleofgrom Tunnel"},
    {"audio/_systems/audiotag/region/dgo_tag_spot_parkinggarage_flowtopia", "Spot Parkinggarage Flowtopia"},
    {"audio/_systems/audiotag/region/dgo_tag_spot_parkinggarage_sanvannews", "Spot Parkinggarage Sanvannews"},
};

inline constexpr const char* kDefaultAudioRegion = "audio/_systems/audiotag/region/dgo_tag_reg_mpr_beach";

} // namespace xl
